export const eventCategories = [
  'Business',
  'Food',
  'Health & Lifestyle',
  'Music',
  'Vehicle',
  'Charity',
  'Community',
  'Fashion',
  'Film',
  'Home',
  'Hobbies',
  'Performing & Visual Arts',
  'Politics',
  'Spirituality',
  'School',
  'Science & Technology',
  'Holiday',
  'Sports & Fitness',
  'Travel',
  'Outdoor & Recreation',
  'Other',
];
